# Python
[Installation](https://www.python.org/downloads/)
- Python is a general-purpose programming language 
- It is a very popular programming language for data science. 
- Quick and easy to use for its simple syntax. Effective systems integration.
- Large number of analytical libraries that can be utilized easily for Data Science purposes.

Recommneded Python environment:
- [Anaconda](https://www.anaconda.com/products/individual)
- IDE: [IDLE](https://docs.python.org/3/library/idle.html), [PyCHarm](https://www.jetbrains.com/pycharm/), [Spyder](https://www.spyder-ide.org/)


# Tutorial

In [2]:
message = "Hello 315!"
if True:
    print(message)

Hello 315!


## Useful Data Structures:

### Lists

In [40]:
#simple list of items
mylist = ["computer", "tv", "desk"]
print(type(mylist))
#ordered list
print("mylist[0]: ", mylist[0])
#changeable
mylist[2] = "phone"
mylist.append("computer")
print("mylist: ",mylist)
#multiple data types
mylist2 = ["str", 34, True, False, [2,3]]

<class 'list'>
mylist[0]:  computer
mylist:  ['computer', 'tv', 'phone', 'computer']


### Set

In [21]:
myset = {"computer", "tv", "desk"}
print(type(myset))
#unordered
print(myset[0])
#items cannot be changed
#no duplicate
myset.add("phone")
print("myset: ",myset)
myset.add("tv")
print("myset: ",myset)
myset.remove("desk")
print("myset: ",myset)
#multiple data types
myset2 = {"str", 34, True, False}

<class 'set'>
myset:  {'computer', 'tv', 'desk', 'phone'}
myset:  {'computer', 'tv', 'desk', 'phone'}
myset:  {'computer', 'tv', 'phone'}


### Tuple

In [1]:
mytuple = ("computer", "tv", "desk")
print(type(mytuple))
#ordered
print("mytuple[1]: ", mytuple[1])
#items cannot be changed
mytuple = mytuple + ("phone",)
print("mytuple: ", mytuple)
#multiple data types
mytuple2 = ("str", 34, True, False)

<class 'tuple'>
mytuple[1]:  tv
mytuple:  ('computer', 'tv', 'desk', 'phone')


### Dictionary

In [33]:
mydict = {
    "key1": 0,
    "key2": 1,
    "key3": "Value0"
}
print(type(mydict))
#ordered with keys
print("mydict[""key2""]: ", mydict["key2"])
#changeable
mydict["key2"] = 3
print("mydict[""key2""]: ", mydict["key2"])
#no duplicated keys
mydict["key4"] = True
print("mydict: ", mydict)

<class 'dict'>
mydict[key2]:  1
mydict[key2]:  3
mydict:  {'key1': 0, 'key2': 3, 'key3': 'Value0', 'key4': True}


- List is a collection which is ordered and changeable. Allows duplicate members.
- Set is a collection which is unordered and unindexed. No duplicate members.
- Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
- Dictionary is a collection which is unordered and changeable. No duplicate members.

In [45]:
tuple_to_list = list(mytuple)
print("tuple_to_list: ", tuple_to_list)
list_to_set = set(mylist)
print("list_to_set: ", list_to_set)

tuple_to_list:  ['computer', 'tv', 'desk', 'phone']
list_to_set:  {'computer', 'tv', 'phone'}


### Numpy
- NumPy is a Python library used for working with arrays.
- Very fast, practical, large number of intgerated functions

In [7]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
arr2 = np.array([1, 2, 3.0, "A", 5])
print(arr2)
arr3 = np.array([1, 2, 3.0, 4, 5])
print(arr3)

[1 2 3 4 5]
<class 'numpy.ndarray'>
['1' '2' '3.0' 'A' '5']
[1. 2. 3. 4. 5.]


In [50]:
#transform any structure to ndarray
arr4 = np.array(mylist2)
print(arr4)

['str' 34 True False list([2, 3])]


In [56]:
#Multidimensional
arr5 = np.zeros((2,3,4))
print("arr5: \n", arr5)
arr6 = np.array([[[1,2,3]],[[3,2,1]]])
print("arr6: \n", arr6)
print("arr6 shape:", arr6.shape)

arr5: 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
arr6: 
 [[[1 2 3]]

 [[3 2 1]]]
arr6 shape: (2, 1, 3)


In [58]:
#Element access
myarr = np.arange(1,20,2)
print("myarr: ", myarr)
print("myarr sliced: ", myarr[2:8:2])

myarr:  [ 1  3  5  7  9 11 13 15 17 19]
myarr sliced:  [ 5  9 13]


In [9]:
import time

x1 = np.arange(10000).reshape((-1,1))
x2 = np.arange(10000).reshape((-1,1))

list_product = np.zeros((10000,10000))
t1 = time.time()
for i, x1_i in enumerate(x1):
    for j, x2_j in enumerate(x2):
        list_product[i,j] = x1_i*x2_j
t2 = time.time()
t3 = time.time()
list_product2 = np.dot(x1, x2.T)
t4 = time.time()
print("Execution as a list: {:.3f} sec.".format((t2-t1)))
print("Execution as a np  : {:.3f} sec".format((t4-t3)))

Execution as a list: 86.496 sec.
Execution as a np  : 0.578 sec


In [35]:
np.all(list_product==list_product2)

True

### Data manipulation

#### Input files

In [60]:
import csv

def read_from_csv(file_name):
    """
    Function to read from file
    using csv library
    """
    record = []
    with open(file_name) as input_file:
        lines = csv.reader(input_file, delimiter=',')
        for row in lines:
            print(row)
            record.append(row)
    return record

content = read_from_csv("document.csv")

['ID0', ' 23', ' 34', ' 45', ' 19']
['ID1', ' 12', ' 45', ' 11', ' 20']
['ID2', ' 01', ' 02', ' 03', ' 04']


In [65]:
content_dict = {}
for id_data in content:
    content_dict[str(id_data[0])] = np.array(id_data[1:]).astype(np.int)
print("content_dict: ", content_dict)

content_dict:  {'ID0': array([23, 34, 45, 19]), 'ID1': array([12, 45, 11, 20]), 'ID2': array([1, 2, 3, 4])}


#### Iterations

In [67]:
for item in content_dict["ID0"]:
    print(item)
print("-------")
for index, item in enumerate(content_dict["ID0"]):
    print(index, ": ", item)

23
34
45
19
-------
0 :  23
1 :  34
2 :  45
3 :  19


In [77]:
import itertools #iterators for efficient iterating
#Very useful for Combinatoric iterators

for value in itertools.permutations(content_dict["ID2"]):
    #generate all possible permutations of an iterable
    print(value)
    
for value in itertools.combinations(content_dict["ID2"],4):
    #generate  all the possible combinations(without replacement) 
    #of the iterable passed in arguments in the specified group size in sorted order.
    print(value)
    
for value in itertools.combinations_with_replacement(content_dict["ID2"],3):
    #generate  all the possible combinations of the iterable 
    #items passed in arguments in the specified group size.
    print(value)

In [81]:
#Illustration of comprehensive lists
list0 = []
for items in content_dict["ID0"]:
    if items > 30:
        list0.append(items)
    else:
        list0.append(-1)
print("list0", list0)
list1 = [items if items>30 else -1 for items in content_dict["ID0"]]
print("list1", list1)

list0 [-1, 34, 45, -1]
list1 [-1, 34, 45, -1]


In [82]:
def isokay(number):
    if number > 30:
        return number
    else:
        return -1
list2 = [isokay(items) for items in content_dict["ID0"]]
print("list2", list2)

list2 [-1, 34, 45, -1]


#### Sorting

In [86]:
l1 = content_dict["ID0"]
print("l1: ", l1)
print("l1 sorted: ", sorted(l1))

l1:  [23 34 45 19]
l1 sorted:  [19, 23, 34, 45]


In [95]:
l2 = ["phone", "screen", "tv", "computer", "keyboard"]
print("Sort alphabetically: ", sorted(l2)) 

print("Sort length: ", sorted(l2, key=len))

def last_pos(x):
    return x[-1]
print("Sort last character: ", sorted(l2, key=last_pos))
print("Sort last character: ", sorted(l2, key=lambda x:x[-1]))

Sort alphabetically:  ['computer', 'keyboard', 'phone', 'screen', 'tv']
Sort length:  ['tv', 'phone', 'screen', 'computer', 'keyboard']
Sort last character:  ['keyboard', 'phone', 'screen', 'computer', 'tv']
Sort last character:  ['keyboard', 'phone', 'screen', 'computer', 'tv']


In [99]:
#lambda function
f_add = lambda x, y:x+y
print("Result: ", f_add(1,2))
#Lambda is an anonymous function (without a name), restricted to a single expression

Result:  3


#### Pandas library 
Pandas is a very good library for handling large representation of complex data collections

- Calculate statistics and answer questions about the data, like average, inter-columns correlations, distributions of items...
- Good handle on tabular data with heterogeneously-typed columns.
- Visualize the data with help from Matplotlib. 
- Efficient storage and reading data (CSV, json, databases...)

In [154]:
import pandas as pd

dFrame = pd.read_csv("mymovies.csv")
dFrame

movieId                          title  year watched  \
0       101                      Toy Story  1995     yes   
1       102                        Jumanji  2017      no   
2       103               Grumpier Old Men  1995     yes   
3       104                Dangerous Minds  1995     yes   
4       105                  Mortal Kombat  1997     yes   
5       106                     To Die For  1995      no   
6       107  How to Make an American Quilt  1995      no   
7       108                          Seven  1995     yes   
8       109                     Pocahontas  1995     yes   
9       110          Home for the Holidays  1995      no   
10      111                 Les Miserables  2012      no   

                                         genres  rating  
0   Adventure|Animation|Children|Comedy|Fantasy      10  
1                    Adventure|Children|Fantasy       8  
2                                Comedy|Romance       6  
3                                         Drama       6  
4                      Action|Adventure|Fantasy       2  
5                         Comedy|Drama|Thriller       7  
6                                 Drama|Romance       6  
7                              Mystery|Thriller      10  
8      Animation|Children|Drama|Musical|Romance      10  
9                                         Drama       8  
10                                    Drama|War       9

In [110]:
print(dFrame.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  11 non-null     int64 
 1   title    11 non-null     object
 2   watched  11 non-null     object
 3   genres   11 non-null     object
 4   rating   11 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 568.0+ bytes
None


In [105]:
#extract genres
genres_set = set() #no duplicates
for i in dFrame.index:
    line = str(dFrame.at[i, 'genres']) #grab item at row i and column 'genres'
    genres_set.update(line.split('|')) #iterable
print(genres_set)

{'War', 'Fantasy', 'Action', 'Adventure', 'Musical', 'Thriller', 'Mystery', 'Comedy', 'Animation', 'Romance', 'Drama', 'Children'}


In [113]:
#Extract columns needed
DF2 = dFrame[['watched', 'rating']]

watched  rating
0      yes      10
1       no       8
2      yes       6
3      yes       6
4      yes       2
5       no       7
6       no       6
7      yes      10
8      yes      10
9       no       8
10      no       9

In [115]:
#Extract rows needed
dFrame.iloc[6:8]

movieId                                 title watched            genres  \
6      107  How to Make an American Quilt (1995)      no     Drama|Romance   
7      108           Seven (a.k.a. Se7en) (1995)     yes  Mystery|Thriller   

   rating  
6       6  
7      10

In [117]:
#Conditional selection
dFrame[dFrame['rating']>8]

movieId                        title watched  \
0       101             Toy Story (1995)     yes   
7       108  Seven (a.k.a. Se7en) (1995)     yes   
8       109            Pocahontas (1995)     yes   
10      111        Misérables,Les (1995)      no   

                                         genres  rating  
0   Adventure|Animation|Children|Comedy|Fantasy      10  
7                              Mystery|Thriller      10  
8      Animation|Children|Drama|Musical|Romance      10  
10                                    Drama|War       9

In [123]:
#Let's merge!
dFrame[['title','rating']][dFrame['rating']>8].iloc[-2:]

title  rating
8       Pocahontas (1995)      10
10  Misérables,Les (1995)       9

In [130]:
#Statistical operations
print("Mean rating: {:.2f}".format(dFrame['rating'].mean()))
print("Watched movies: {}".format(dFrame['watched'][dFrame['watched']=='yes'].count()))

Mean rating: 7.45
Watched movies: 6


In [136]:
dFrame['year'].value_counts()

1995    8
1997    1
2012    1
2017    1
Name: year, dtype: int64

In [141]:
dFrame.groupby('watched').min()

movieId                  title  year                      genres  \
watched                                                                     
no           102  Home for the Holidays  1995  Adventure|Children|Fantasy   
yes          101        Dangerous Minds  1995    Action|Adventure|Fantasy   

         rating  
watched          
no            6  
yes           2

In [155]:
import copy
dFrame2 = copy.deepcopy(dFrame)
dFrame2['rating'] = dFrame2['rating'].apply(lambda x:min(x,5))

In [157]:
dFrame2

movieId                          title  year watched  \
0       101                      Toy Story  1995     yes   
1       102                        Jumanji  2017      no   
2       103               Grumpier Old Men  1995     yes   
3       104                Dangerous Minds  1995     yes   
4       105                  Mortal Kombat  1997     yes   
5       106                     To Die For  1995      no   
6       107  How to Make an American Quilt  1995      no   
7       108                          Seven  1995     yes   
8       109                     Pocahontas  1995     yes   
9       110          Home for the Holidays  1995      no   
10      111                 Les Miserables  2012      no   

                                         genres  rating  
0   Adventure|Animation|Children|Comedy|Fantasy       5  
1                    Adventure|Children|Fantasy       5  
2                                Comedy|Romance       5  
3                                         Drama       5  
4                      Action|Adventure|Fantasy       2  
5                         Comedy|Drama|Thriller       5  
6                                 Drama|Romance       5  
7                              Mystery|Thriller       5  
8      Animation|Children|Drama|Musical|Romance       5  
9                                         Drama       5  
10                                    Drama|War       5

In [158]:
dFrame2.to_csv("new_document.csv")