In [ ]:
message = "Hello World!"
message = 1.0 
if True:
    print(message)

In [3]:
myList = ["computer", "tv", "phone"]
print("myList[0]:", myList[0])

myList[0]: computer


In [4]:
import numpy as np
list1 = [1,2,3,4]
arr1 = np.array(list1)
# print(type(arr1))
arr2 = np.array(['1','2'])

In [5]:
arr5 = np.zeros((3,5,2))
print("array shape is: ", arr5.shape)
list1 = [[[41,72,96]]]
print(list1)
print(list1[0][0][2])
arr6 = np.array(list1)
print(arr6.shape)

array shape is:  (3, 5, 2)
[[[41, 72, 96]]]
96
(1, 1, 3)


In [6]:
arr = np.arange(0, 20)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
print("\nFrom 5:10\n {}" .format(arr[5:10]))
print("\nFrom start:10\n {}" .format(arr[:10]))
print("\nFrom 5:end\n {}".format(arr[5:]))
print("\n-------------> WEIRD CASE 5:0 \n {}".format(arr[5:0]))
print("\nFrom 5:third-from-last\n {}".format(arr[5:-2]))
print("\nFrom 10:end, stepsize = 2\n {}" .format(arr[10::2]))
print("\nFrom end GO BACK, backstep= 1\n {}" .format(arr[::-1]))
print("\nFrom end GO BACK, backstep= 2\n {}" .format(arr[::-2]))


From 5:10
 [5 6 7 8 9]

From start:10
 [0 1 2 3 4 5 6 7 8 9]

From 5:end
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

-------------> WEIRD CASE 5:0 
 []

From 5:third-from-last
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17]

From 10:end, stepsize = 2
 [10 12 14 16 18]

From end GO BACK, backstep= 1
 [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

From end GO BACK, backstep= 2
 [19 17 15 13 11  9  7  5  3  1]


In [8]:
arr2D = np.zeros((14,12))
print(arr2D.reshape((-1, 12))) # just have specify one dimension, then use -1 for the other and Python will automatically interpret and calculate the size of the other dimension

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
# much faster computation
import numpy as np
import time 

x1 = np.arange (10000).reshape((-1,1))
x2 = np.arange (10000).reshape((-1,1))

list_product = np.zeros((10000,10000))

t1 = time.time()

for i, x1j in enumerate(x1):
    for j, x2j in enumerate(x2):
        list_product[i,j] = x1j*x2j

t2 = time.time()
t3 = time.time()
list_product2 = np.dot(x1, x2.T)
t4 = time.time()
print("Execution as a list: {:.3f} sec.".format((t2-t1)))
print("Execution as a np  : {:.3f} sec.".format((t4-t3)))

Execution as a list: 93.825 sec.
Execution as a np  : 0.403 sec.


In [7]:
print("Compare the 2 products:")
np.all(list_product == list_product2)
print("numpy dot product is much faster, by an order of {}".format((t2-t1)/(t4-t3)))

Compare the 2 products:
numpy dot product is much faster, by an order of 232.66896380470385


In [6]:
list1 = ['a','b','c']
for i in list1:
    print(i)
print("\n")
for i in range(3):
    print(i)
print("\n")
for i, x in enumerate(list1):
    print(i, x)

a
b
c


0
1
2


0 a
1 b
2 c
